import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        {/* Texture overlay */}
        <div 
          className="fixed inset-0 pointer-events-none z-0"
          style={{
            backgroundImage: 'url(/texture.svg)',
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            opacity: 0.5, // Adjust this to control visibility
            filter: 'saturate(0) brightness(0.25) contrast(1.01)',
          }}
        />
        
        {/* Content wrapper with higher z-index */}
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
